R"(

// Resolution of frustum item grid
#define REN_GRID_RES_X )" AS_STR(REN_GRID_RES_X) R"(
#define REN_GRID_RES_Y )" AS_STR(REN_GRID_RES_Y) R"(
#define REN_GRID_RES_Z )" AS_STR(REN_GRID_RES_Z) R"(

// Attribute location
#define REN_VTX_POS_LOC )" AS_STR(REN_VTX_POS_LOC) R"(
#define REN_VTX_NOR_LOC )" AS_STR(REN_VTX_NOR_LOC) R"(
#define REN_VTX_TAN_LOC )" AS_STR(REN_VTX_TAN_LOC) R"(
#define REN_VTX_UV1_LOC )" AS_STR(REN_VTX_UV1_LOC) R"(
#define REN_VTX_AUX_LOC )" AS_STR(REN_VTX_AUX_LOC) R"(

// Texture binding
#define REN_MAT_TEX0_SLOT   )" AS_STR(REN_MAT_TEX0_SLOT) R"(
#define REN_MAT_TEX1_SLOT   )" AS_STR(REN_MAT_TEX1_SLOT) R"(
#define REN_MAT_TEX2_SLOT   )" AS_STR(REN_MAT_TEX2_SLOT) R"(
#define REN_SHAD_TEX_SLOT   )" AS_STR(REN_SHAD_TEX_SLOT) R"(
#define REN_LMAP_SH_SLOT    )" AS_STR(REN_LMAP_SH_SLOT) R"(
#define REN_DECAL_TEX_SLOT  )" AS_STR(REN_DECAL_TEX_SLOT) R"(
#define REN_SSAO_TEX_SLOT   )" AS_STR(REN_SSAO_TEX_SLOT) R"(
#define REN_BRDF_TEX_SLOT   )" AS_STR(REN_BRDF_TEX_SLOT) R"(
#define REN_LIGHT_BUF_SLOT  )" AS_STR(REN_LIGHT_BUF_SLOT) R"(
#define REN_DECAL_BUF_SLOT  )" AS_STR(REN_DECAL_BUF_SLOT) R"(
#define REN_CELLS_BUF_SLOT  )" AS_STR(REN_CELLS_BUF_SLOT) R"(
#define REN_ITEMS_BUF_SLOT  )" AS_STR(REN_ITEMS_BUF_SLOT) R"(
#define REN_INST_BUF_SLOT   )" AS_STR(REN_INST_BUF_SLOT) R"(
#define REN_ENV_TEX_SLOT    )" AS_STR(REN_ENV_TEX_SLOT) R"(
#define REN_MOMENTS0_TEX_SLOT )" AS_STR(REN_MOMENTS0_TEX_SLOT) R"(
#define REN_MOMENTS1_TEX_SLOT )" AS_STR(REN_MOMENTS1_TEX_SLOT) R"(
#define REN_MOMENTS2_TEX_SLOT )" AS_STR(REN_MOMENTS2_TEX_SLOT) R"(
#define REN_MOMENTS0_MS_TEX_SLOT )" AS_STR(REN_MOMENTS0_MS_TEX_SLOT) R"(
#define REN_MOMENTS1_MS_TEX_SLOT )" AS_STR(REN_MOMENTS1_MS_TEX_SLOT) R"(
#define REN_MOMENTS2_MS_TEX_SLOT )" AS_STR(REN_MOMENTS2_MS_TEX_SLOT) R"(
#define REN_NOISE_TEX_SLOT )" AS_STR(REN_NOISE_TEX_SLOT) R"(

#define REN_ALPHATEST_TEX_SLOT )" AS_STR(REN_ALPHATEST_TEX_SLOT) R"(

#define REN_BASE0_TEX_SLOT )" AS_STR(REN_BASE0_TEX_SLOT) R"(
#define REN_BASE1_TEX_SLOT )" AS_STR(REN_BASE1_TEX_SLOT) R"(

#define REN_REFL_DEPTH_TEX_SLOT )" AS_STR(REN_REFL_DEPTH_TEX_SLOT) R"(
#define REN_REFL_NORM_TEX_SLOT  )" AS_STR(REN_REFL_NORM_TEX_SLOT) R"(
#define REN_REFL_SPEC_TEX_SLOT  )" AS_STR(REN_REFL_SPEC_TEX_SLOT) R"(
#define REN_REFL_PREV_TEX_SLOT  )" AS_STR(REN_REFL_PREV_TEX_SLOT) R"(
#define REN_REFL_SSR_TEX_SLOT   )" AS_STR(REN_REFL_SSR_TEX_SLOT) R"(
#define REN_REFL_ENV_TEX_SLOT   )" AS_STR(REN_REFL_ENV_TEX_SLOT) R"(
#define REN_REFL_BRDF_TEX_SLOT  )" AS_STR(REN_REFL_BRDF_TEX_SLOT) R"(
#define REN_REFL_DEPTH_LOW_TEX_SLOT )" AS_STR(REN_REFL_DEPTH_LOW_TEX_SLOT) R"(

#define REN_U_M_MATRIX_LOC  )" AS_STR(REN_U_M_MATRIX_LOC) R"(
#define REN_U_INSTANCES_LOC )" AS_STR(REN_U_INSTANCES_LOC) R"(

#define REN_UB_SHARED_DATA_LOC  )" AS_STR(REN_UB_SHARED_DATA_LOC) R"(

// Shader output location
#define REN_OUT_COLOR_INDEX )" AS_STR(REN_OUT_COLOR_INDEX) R"(
#define REN_OUT_NORM_INDEX  )" AS_STR(REN_OUT_NORM_INDEX) R"(
#define REN_OUT_SPEC_INDEX  )" AS_STR(REN_OUT_SPEC_INDEX) R"(
#define REN_OUT_VELO_INDEX  )" AS_STR(REN_OUT_VELO_INDEX) R"(

// Shadow resolution
#define REN_SHAD_RES_PC         )" AS_STR(REN_SHAD_RES_PC) R"(
#define REN_SHAD_RES_ANDROID    )" AS_STR(REN_SHAD_RES_ANDROID) R"(
)"
#ifdef __ANDROID__
R"(#define REN_SHAD_RES REN_SHAD_RES_ANDROID
)"
#else
R"(#define REN_SHAD_RES REN_SHAD_RES_PC
)"
#endif
R"(

// Shadow cascades definition
#define REN_SHAD_CASCADE0_DIST      )" AS_STR(REN_SHAD_CASCADE0_DIST) R"(
#define REN_SHAD_CASCADE0_SAMPLES   )" AS_STR(REN_SHAD_CASCADE0_SAMPLES) R"(
#define REN_SHAD_CASCADE1_DIST      )" AS_STR(REN_SHAD_CASCADE1_DIST) R"(
#define REN_SHAD_CASCADE1_SAMPLES   )" AS_STR(REN_SHAD_CASCADE1_SAMPLES) R"(
#define REN_SHAD_CASCADE2_DIST      )" AS_STR(REN_SHAD_CASCADE2_DIST) R"(
#define REN_SHAD_CASCADE2_SAMPLES   )" AS_STR(REN_SHAD_CASCADE2_SAMPLES) R"(
#define REN_SHAD_CASCADE3_DIST      )" AS_STR(REN_SHAD_CASCADE3_DIST) R"(
#define REN_SHAD_CASCADE3_SAMPLES   )" AS_STR(REN_SHAD_CASCADE3_SAMPLES) R"(
#define REN_SHAD_CASCADE_SOFT       )" AS_STR(REN_SHAD_CASCADE_SOFT) R"(

#define REN_MAX_OBJ_COUNT			)" AS_STR(REN_MAX_OBJ_COUNT) R"(
#define REN_MAX_BATCH_SIZE			)" AS_STR(REN_MAX_BATCH_SIZE) R"(

#define REN_MAX_INSTANCES_TOTAL     )" AS_STR(REN_MAX_INSTANCES_TOTAL) R"(
#define REN_MAX_SHADOWMAPS_TOTAL    )" AS_STR(REN_MAX_SHADOWMAPS_TOTAL) R"(
#define REN_MAX_PROBES_TOTAL        )" AS_STR(REN_MAX_PROBES_TOTAL) R"(
#define REN_SKIN_REGION_SIZE        )" AS_STR(REN_SKIN_REGION_SIZE) R"(
#define REN_MAX_SKIN_XFORMS_TOTAL   )" AS_STR(REN_MAX_SKIN_XFORMS_TOTAL) R"(
#define REN_MAX_SKIN_REGIONS_TOTAL  )" AS_STR(REN_MAX_SKIN_REGIONS_TOTAL) R"(
#define REN_MAX_SKIN_VERTICES_TOTAL )" AS_STR(REN_MAX_SKIN_VERTICES_TOTAL) R"(

#define REN_MAX_SHADOW_BATCHES  )" AS_STR(REN_MAX_SHADOW_BATCHES) R"(
#define REN_MAX_MAIN_BATCHES    )" AS_STR(REN_MAX_MAIN_BATCHES) R"(

#define REN_CELLS_COUNT (REN_GRID_RES_X * REN_GRID_RES_Y * REN_GRID_RES_Z)

#define REN_MAX_LIGHTS_PER_CELL )" AS_STR(REN_MAX_LIGHTS_PER_CELL) R"(
#define REN_MAX_DECALS_PER_CELL )" AS_STR(REN_MAX_DECALS_PER_CELL) R"(
#define REN_MAX_PROBES_PER_CELL )" AS_STR(REN_MAX_PROBES_PER_CELL) R"(
#define REN_MAX_ITEMS_PER_CELL  )" AS_STR(REN_MAX_ITEMS_PER_CELL) R"(

#define REN_MAX_LIGHTS_TOTAL )" AS_STR(REN_MAX_LIGHTS_TOTAL) R"(
#define REN_MAX_DECALS_TOTAL )" AS_STR(REN_MAX_DECALS_TOTAL) R"(
#define REN_MAX_ITEMS_TOTAL )" AS_STR(REN_MAX_ITEMS_TOTAL) R"(

#define REN_OIT_DISABLED            )" AS_STR(REN_OIT_DISABLED) R"(
#define REN_OIT_MOMENT_BASED        )" AS_STR(REN_OIT_MOMENT_BASED) R"(
#define REN_OIT_WEIGHTED_BLENDED    )" AS_STR(REN_OIT_WEIGHTED_BLENDED) R"(

#define REN_OIT_MOMENT_RENORMALIZE  )" AS_STR(REN_OIT_MOMENT_RENORMALIZE) R"(

#define REN_OIT_MODE REN_OIT_DISABLED

#define FLT_EPS 0.0000001

struct ShadowMapRegion {
    vec4 transform;
    mat4 clip_from_world;
};

struct ProbeItem {
    vec4 pos_and_radius;
    vec4 unused_and_layer;
    vec4 sh_coeffs[3];
};

struct SharedData {
    mat4 uViewMatrix, uProjMatrix, uViewProjMatrix, uViewProjPrevMatrix;
    mat4 uInvViewMatrix, uInvProjMatrix, uInvViewProjMatrix, uDeltaMatrix;
    ShadowMapRegion uShadowMapRegions[REN_MAX_SHADOWMAPS_TOTAL];
    vec4 uSunDir, uSunCol, uTaaInfo;
    vec4 uClipInfo, uCamPosAndGamma;
    vec4 uResAndFRes, uTranspParamsAndTime;
    vec4 uWindScroll, uWindScrollPrev;
    ProbeItem uProbes[REN_MAX_PROBES_TOTAL];
};

)"