#ifndef ELLIPSOID_INTERFACE_H
#define ELLIPSOID_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(Ellipsoid)

DEF_CONST_INT(U_M_MATRIX_LOC, 0)

INTERFACE_END

#endif // ELLIPSOID_INTERFACE_H