#ifndef GI_WRITE_INDIR_RT_DISPATCH_INTERFACE_H
#define GI_WRITE_INDIR_RT_DISPATCH_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(GIWriteIndirRTDispatch)

const int RAY_COUNTER_SLOT = 0;
const int INDIR_ARGS_SLOT = 1;

INTERFACE_END

#endif // GI_WRITE_INDIR_RT_DISPATCH_INTERFACE_H