#ifndef GI_WRITE_INDIRECT_ARGS_INTERFACE_H
#define GI_WRITE_INDIRECT_ARGS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(GIWriteIndirectArgs)

const int RAY_COUNTER_SLOT = 0;
const int INDIR_ARGS_SLOT = 1;

INTERFACE_END

#endif // GI_WRITE_INDIRECT_ARGS_INTERFACE_H