#ifndef OIT_SCHEDULE_RAYS_INTERFACE_H
#define OIT_SCHEDULE_RAYS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(OITScheduleRays)

const int OIT_DEPTH_BUF_SLOT = 3;

const int RAY_COUNTER_SLOT = 1;
const int RAY_LIST_SLOT = 2;

INTERFACE_END

#endif // OIT_SCHEDULE_RAYS_INTERFACE_H