#ifndef RT_DIFFUSE_WRITE_INDIRECT_ARGS_INTERFACE_H
#define RT_DIFFUSE_WRITE_INDIRECT_ARGS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(RTDiffuseWriteIndirectArgs)

const uint RAY_COUNTER_SLOT = 0;
const uint INDIR_ARGS_SLOT = 1;

INTERFACE_END

#endif // RT_DIFFUSE_WRITE_INDIRECT_ARGS_INTERFACE_H