#ifndef SKYDOME_INTERFACE_H
#define SKYDOME_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(Skydome)

DEF_CONST_INT(U_M_MATRIX_LOC, 0)
DEF_CONST_INT(ENV_TEX_SLOT, 1)

INTERFACE_END

#endif // SKYDOME_INTERFACE_H