#ifndef SSR_VS_DEPTH_INTERFACE_H
#define SSR_VS_DEPTH_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(SSRVSDepth)

struct Params {
    IVEC2_TYPE resolution;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 0)
DEF_CONST_INT(OUT_VS_DEPTH_IMG_SLOT, 1)

INTERFACE_END

#endif // SSR_VS_DEPTH_INTERFACE_H