#ifndef SSR_CLASSIFY_TILES_INTERFACE_H
#define SSR_CLASSIFY_TILES_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(SSRClassifyTiles)

struct Params {
    UVEC2_TYPE img_size;
    VEC2_TYPE thresholds;
    UVEC2_TYPE samples_and_guided;
    UINT_TYPE frame_index;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 2)
DEF_CONST_INT(NORM_TEX_SLOT, 3)
DEF_CONST_INT(VARIANCE_TEX_SLOT, 4)
DEF_CONST_INT(RAY_COUNTER_SLOT, 5)
DEF_CONST_INT(RAY_LIST_SLOT, 6)
DEF_CONST_INT(TILE_LIST_SLOT, 7)
DEF_CONST_INT(SOBOL_BUF_SLOT, 8)
DEF_CONST_INT(SCRAMLING_TILE_BUF_SLOT, 9)
DEF_CONST_INT(RANKING_TILE_BUF_SLOT, 10)

DEF_CONST_INT(REFL_IMG_SLOT, 0)
DEF_CONST_INT(NOISE_IMG_SLOT, 1)

INTERFACE_END

#endif // SSR_CLASSIFY_TILES_INTERFACE_H