#ifndef BLIT_SSR_COMPOSE2_INTERFACE_GLSL
#define BLIT_SSR_COMPOSE2_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(SSRCompose2)

struct Params {
    VEC4_TYPE transform;
};

DEF_CONST_INT(SPEC_TEX_SLOT, 0)
DEF_CONST_INT(DEPTH_TEX_SLOT, 1)
DEF_CONST_INT(NORM_TEX_SLOT, 2)
DEF_CONST_INT(REFL_TEX_SLOT, 3)
DEF_CONST_INT(BRDF_TEX_SLOT, 4)

INTERFACE_END

#endif // BLIT_SSR_COMPOSE2_INTERFACE_GLSL