#ifndef DEBUG_VELOCITY_INTERFACE_GLSL
#define DEBUG_VELOCITY_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(DebugVelocity)

struct Params {
    UVEC2_TYPE img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(VELOCITY_TEX_SLOT, 1)

DEF_CONST_INT(OUT_IMG_SLOT, 0)

INTERFACE_END

#endif // DEBUG_VELOCITY_INTERFACE_GLSL