#ifndef DEPTH_HIERARCHY_INTERFACE_H
#define DEPTH_HIERARCHY_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(DepthHierarchy)

struct Params {
    IVEC4_TYPE depth_size;
    VEC4_TYPE clip_info;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 64)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 64)

DEF_CONST_INT(DEPTH_TEX_SLOT, 14)
DEF_CONST_INT(ATOMIC_CNT_SLOT, 15)

DEF_CONST_INT(DEPTH_IMG_SLOT, 0)

INTERFACE_END

#endif // DEPTH_HIERARCHY_INTERFACE_H