#ifndef GBUFFER_SHADE_INTERFACE_GLSL
#define GBUFFER_SHADE_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(GBufferShade)

struct Params {
    UVEC2_TYPE img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 1)
DEF_CONST_INT(ALBEDO_TEX_SLOT, 2)
DEF_CONST_INT(NORMAL_TEX_SLOT, 3)
DEF_CONST_INT(SPECULAR_TEX_SLOT, 4)

DEF_CONST_INT(SHADOW_TEX_SLOT, 5)
DEF_CONST_INT(SSAO_TEX_SLOT, 6)
DEF_CONST_INT(LIGHT_BUF_SLOT, 7)
DEF_CONST_INT(DECAL_BUF_SLOT, 8)
DEF_CONST_INT(CELLS_BUF_SLOT, 9)
DEF_CONST_INT(ITEMS_BUF_SLOT, 10)

DEF_CONST_INT(OUT_COLOR_IMG_SLOT, 0)

INTERFACE_END

#endif // GBUFFER_SHADE_INTERFACE_GLSL