#ifndef GI_PREFILTER_INTERFACE_GLSL
#define GI_PREFILTER_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(GIPrefilter)

struct Params {
    VEC4_TYPE rotator;
    UVEC2_TYPE img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 2)
DEF_CONST_INT(NORM_TEX_SLOT, 3)
DEF_CONST_INT(AVG_GI_TEX_SLOT, 4)
DEF_CONST_INT(GI_TEX_SLOT, 5)
DEF_CONST_INT(VARIANCE_TEX_SLOT, 6)
DEF_CONST_INT(SAMPLE_COUNT_TEX_SLOT, 7)
DEF_CONST_INT(TILE_LIST_BUF_SLOT, 8)

DEF_CONST_INT(OUT_GI_IMG_SLOT, 0)
DEF_CONST_INT(OUT_VARIANCE_IMG_SLOT, 1)

INTERFACE_END

#endif // GI_PREFILTER_INTERFACE_GLSL