#ifndef GI_TRACE_SS_INTERFACE_H
#define GI_TRACE_SS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(GITraceSS)

struct Params {
    UVEC4_TYPE resolution;
    UINT_TYPE frame_index;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 4)
DEF_CONST_INT(COLOR_TEX_SLOT, 5)
DEF_CONST_INT(NORM_TEX_SLOT, 6)
DEF_CONST_INT(IN_RAY_LIST_SLOT, 7)
DEF_CONST_INT(NOISE_TEX_SLOT, 8)

DEF_CONST_INT(OUT_GI_IMG_SLOT, 0)
DEF_CONST_INT(INOUT_RAY_COUNTER_SLOT, 2)
DEF_CONST_INT(OUT_RAY_LIST_SLOT, 3)

INTERFACE_END

#endif // GI_TRACE_SS_INTERFACE_H