#ifndef RECONSTRUCT_NORMALS_INTERFACE_GLSL
#define RECONSTRUCT_NORMALS_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(ReconstructNormals)

struct Params {
    VEC4_TYPE frustum_info;
    VEC4_TYPE clip_info;
    UVEC2_TYPE img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 1)

DEF_CONST_INT(OUT_NORMALS_IMG_SLOT, 0)

INTERFACE_END

#endif // RECONSTRUCT_NORMALS_INTERFACE_GLSL