#ifndef RT_DEBUG_INTERFACE_GLSL
#define RT_DEBUG_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(RTDebug)

struct Params {
    float pixel_spread_angle;
    float _pad[3];
};

struct RayPayload {
    VEC3_TYPE col;
    float cone_width;
};

DEF_CONST_INT(TLAS_SLOT, 0)
DEF_CONST_INT(ENV_TEX_SLOT, 1)
DEF_CONST_INT(GEO_DATA_BUF_SLOT, 2)
DEF_CONST_INT(MATERIAL_BUF_SLOT, 3)
DEF_CONST_INT(VTX_BUF1_SLOT, 4)
DEF_CONST_INT(VTX_BUF2_SLOT, 5)
DEF_CONST_INT(NDX_BUF_SLOT, 6)
DEF_CONST_INT(LMAP_TEX_SLOTS, 7)
DEF_CONST_INT(OUT_IMG_SLOT, 12)

INTERFACE_END

#endif // RT_DEBUG_INTERFACE_GLSL