#ifndef RT_DEBUG_INTERFACE_GLSL
#define RT_DEBUG_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(RTDebug)

struct Params {
    UVEC2_TYPE img_size;
    float pixel_spread_angle;
    float _pad[1];
};

struct RayPayload {
    VEC3_TYPE col;
    float cone_width;
};

DEF_CONST_INT(MAX_STACK_SIZE, 48);

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(TLAS_SLOT, 1)
DEF_CONST_INT(ENV_TEX_SLOT, 2)
DEF_CONST_INT(GEO_DATA_BUF_SLOT, 3)
DEF_CONST_INT(MATERIAL_BUF_SLOT, 4)
DEF_CONST_INT(VTX_BUF1_SLOT, 5)
DEF_CONST_INT(VTX_BUF2_SLOT, 6)
DEF_CONST_INT(NDX_BUF_SLOT, 7)
DEF_CONST_INT(NODES_BUF_SLOT, 8)
DEF_CONST_INT(PRIM_NDX_BUF_SLOT, 9)
DEF_CONST_INT(LMAP_TEX_SLOTS, 9)
DEF_CONST_INT(OUT_IMG_SLOT, 0)

INTERFACE_END

#endif // RT_DEBUG_INTERFACE_GLSL