#ifndef RT_GI_INTERFACE_GLSL
#define RT_GI_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(RTGI)

struct Params {
    UVEC2_TYPE img_size;
    float pixel_spread_angle;
    UINT_TYPE frame_index;
};

struct RayPayload {
    VEC3_TYPE col;
    float cone_width;
};

DEF_CONST_INT(TLAS_SLOT, 0)
DEF_CONST_INT(DEPTH_TEX_SLOT, 1)
DEF_CONST_INT(NORM_TEX_SLOT, 2)
DEF_CONST_INT(ENV_TEX_SLOT, 4)
DEF_CONST_INT(GEO_DATA_BUF_SLOT, 5)
DEF_CONST_INT(MATERIAL_BUF_SLOT, 6)
DEF_CONST_INT(VTX_BUF1_SLOT, 7)
DEF_CONST_INT(VTX_BUF2_SLOT, 8)
DEF_CONST_INT(NDX_BUF_SLOT, 9)
DEF_CONST_INT(RAY_COUNTER_SLOT, 10)
DEF_CONST_INT(RAY_LIST_SLOT, 11)
DEF_CONST_INT(NOISE_TEX_SLOT, 12)
DEF_CONST_INT(LMAP_TEX_SLOTS, 13)
DEF_CONST_INT(OUT_GI_IMG_SLOT, 18)

INTERFACE_END

#endif // RT_GI_INTERFACE_GLSL