#ifndef RT_REFLECTIONS_INTERFACE_H
#define RT_REFLECTIONS_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(RTReflections)

struct Params {
    UVEC2_TYPE img_size;
    float pixel_spread_angle;
    float _pad[1];
};

struct RayPayload {
    VEC3_TYPE col;
    float cone_width;
};

DEF_CONST_INT(TLAS_SLOT, 3)
DEF_CONST_INT(DEPTH_TEX_SLOT, 4)
DEF_CONST_INT(NORM_TEX_SLOT, 5)
DEF_CONST_INT(ENV_TEX_SLOT, 6)
DEF_CONST_INT(GEO_DATA_BUF_SLOT, 7)
DEF_CONST_INT(MATERIAL_BUF_SLOT, 8)
DEF_CONST_INT(VTX_BUF1_SLOT, 9)
DEF_CONST_INT(VTX_BUF2_SLOT, 10)
DEF_CONST_INT(NDX_BUF_SLOT, 11)
DEF_CONST_INT(PRIM_NDX_BUF_SLOT, 12)
DEF_CONST_INT(MESHES_BUF_SLOT, 13)
DEF_CONST_INT(MESH_INSTANCES_BUF_SLOT, 14)
DEF_CONST_INT(RAY_COUNTER_SLOT, 15)
DEF_CONST_INT(RAY_LIST_SLOT, 16)
DEF_CONST_INT(BLAS_BUF_SLOT, 17)
DEF_CONST_INT(TLAS_BUF_SLOT, 18)
DEF_CONST_INT(NOISE_TEX_SLOT, 19)
DEF_CONST_INT(LMAP_TEX_SLOTS, 25)

DEF_CONST_INT(OUT_REFL_IMG_SLOT, 1)
DEF_CONST_INT(OUT_RAYLEN_IMG_SLOT, 2)

INTERFACE_END

#endif // RT_REFLECTIONS_INTERFACE_H