#ifndef RT_SHADOWS_INTERFACE_GLSL
#define RT_SHADOWS_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(RTShadows)

struct Params {
    UVEC2_TYPE img_size;
    float pixel_spread_angle;
    UINT_TYPE frame_index;
};

struct RayPayload {
    VEC3_TYPE col;
    float cone_width;
};

DEF_CONST_INT(TLAS_SLOT, 1)
DEF_CONST_INT(NOISE_TEX_SLOT, 2)
DEF_CONST_INT(DEPTH_TEX_SLOT, 3)
DEF_CONST_INT(NORM_TEX_SLOT, 4)
DEF_CONST_INT(GEO_DATA_BUF_SLOT, 5)
DEF_CONST_INT(MATERIAL_BUF_SLOT, 6)
DEF_CONST_INT(VTX_BUF1_SLOT, 7)
DEF_CONST_INT(VTX_BUF2_SLOT, 8)
DEF_CONST_INT(NDX_BUF_SLOT, 9)
DEF_CONST_INT(TILE_LIST_SLOT, 10)

DEF_CONST_INT(OUT_SHADOW_IMG_SLOT, 0)

INTERFACE_END

#endif // RT_SHADOWS_INTERFACE_GLSL