#ifndef RT_SHADOW_PREPARE_MASK_INTERFACE_GLSL
#define RT_SHADOW_PREPARE_MASK_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(RTShadowPrepareMask)

struct Params {
    UVEC2_TYPE img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 4)

DEF_CONST_INT(HIT_MASK_TEX_SLOT, 1)

DEF_CONST_INT(SHADOW_MASK_BUF_SLOT, 0)

INTERFACE_END

#endif // RT_SHADOW_PREPARE_MASK_INTERFACE_GLSL