#ifndef RT_SHADOW_FILTER_INTERFACE_GLSL
#define RT_SHADOW_FILTER_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(RTShadowFilter)

struct Params {
    UVEC2_TYPE img_size;
    VEC2_TYPE inv_img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 2)
DEF_CONST_INT(NORM_TEX_SLOT, 3)
DEF_CONST_INT(INPUT_TEX_SLOT, 4)
DEF_CONST_INT(TILE_METADATA_BUF_SLOT, 5)

DEF_CONST_INT(OUT_RESULT_IMG_SLOT, 0)

INTERFACE_END

#endif // RT_SHADOW_FILTER_INTERFACE_GLSL