#ifndef RT_SHADOW_CLASSIFY_TILES_INTERFACE_H
#define RT_SHADOW_CLASSIFY_TILES_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(RTShadowClassifyTiles)

struct Params {
    UVEC2_TYPE img_size;
    VEC2_TYPE inv_img_size;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 2)
DEF_CONST_INT(VELOCITY_TEX_SLOT, 3)
DEF_CONST_INT(NORM_TEX_SLOT, 4)
DEF_CONST_INT(HISTORY_TEX_SLOT, 5)
DEF_CONST_INT(PREV_DEPTH_TEX_SLOT, 6)
DEF_CONST_INT(PREV_MOMENTS_TEX_SLOT, 7)
DEF_CONST_INT(RAY_HITS_BUF_SLOT, 8)
DEF_CONST_INT(OUT_TILE_METADATA_BUF_SLOT, 9)

DEF_CONST_INT(OUT_REPROJ_RESULTS_IMG_SLOT, 0)
DEF_CONST_INT(OUT_MOMENTS_IMG_SLOT, 1)

INTERFACE_END

#endif // RT_SHADOW_CLASSIFY_TILES_INTERFACE_H