#ifndef SKINNING_INTERFACE_GLSL
#define SKINNING_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(Skinning)

struct Params {
    UVEC4_TYPE uSkinParams;
    UVEC4_TYPE uShapeParamsCurr;
    UVEC4_TYPE uShapeParamsPrev;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE, 128)

DEF_CONST_INT(IN_VERTICES_SLOT, 0)
DEF_CONST_INT(IN_MATRICES_SLOT, 1)
DEF_CONST_INT(IN_SHAPE_KEYS_SLOT, 2)
DEF_CONST_INT(IN_DELTAS_SLOT, 3)
DEF_CONST_INT(OUT_VERTICES0, 4)
DEF_CONST_INT(OUT_VERTICES1, 5)

INTERFACE_END

#endif // SKINNING_INTERFACE_GLSL