#ifndef SSR_TRACE_HQ_INTERFACE_GLSL
#define SSR_TRACE_HQ_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(SSRTraceHQ)

struct Params {
    UVEC4_TYPE resolution;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 4)
DEF_CONST_INT(COLOR_TEX_SLOT, 5)
DEF_CONST_INT(NORM_TEX_SLOT, 6)
DEF_CONST_INT(IN_RAY_LIST_SLOT, 7)
DEF_CONST_INT(NOISE_TEX_SLOT, 8)

DEF_CONST_INT(OUT_REFL_IMG_SLOT, 0)
DEF_CONST_INT(OUT_RAYLEN_IMG_SLOT, 1)
DEF_CONST_INT(INOUT_RAY_COUNTER_SLOT, 2)
DEF_CONST_INT(OUT_RAY_LIST_SLOT, 3)

INTERFACE_END

#endif // SSR_TRACE_HQ_INTERFACE_GLSL