#ifndef SSR_TRACE_HQ_INTERFACE_GLSL
#define SSR_TRACE_HQ_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(SSRTraceHQ)

struct Params {
    UVEC4_TYPE resolution;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 3)
DEF_CONST_INT(COLOR_TEX_SLOT, 4)
DEF_CONST_INT(NORM_TEX_SLOT, 5)
DEF_CONST_INT(RAY_COUNTER_SLOT, 6)
DEF_CONST_INT(IN_RAY_LIST_SLOT, 7)
DEF_CONST_INT(SOBOL_BUF_SLOT, 8)
DEF_CONST_INT(SCRAMLING_TILE_BUF_SLOT, 9)
DEF_CONST_INT(RANKING_TILE_BUF_SLOT, 10)

DEF_CONST_INT(OUT_REFL_IMG_SLOT, 0)
DEF_CONST_INT(OUT_RAYLEN_IMG_SLOT, 1)
DEF_CONST_INT(OUT_RAY_LIST_SLOT, 2)

INTERFACE_END

#endif // SSR_TRACE_HQ_INTERFACE_GLSL