#ifndef SSR_WRITE_INDIR_RT_DISPATCH_INTERFACE_GLSL
#define SSR_WRITE_INDIR_RT_DISPATCH_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(SSRWriteIndirRTDispatch)

DEF_CONST_INT(RAY_COUNTER_SLOT, 0)
DEF_CONST_INT(INDIR_ARGS_SLOT, 1)

INTERFACE_END

#endif // SSR_WRITE_INDIR_RT_DISPATCH_INTERFACE_GLSL