#ifndef SSR_CLASSIFY_TILES_INTERFACE_GLSL
#define SSR_CLASSIFY_TILES_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(SSRClassifyTiles)

struct Params {
    UVEC2_TYPE img_size;
    VEC2_TYPE thresholds;
    UVEC2_TYPE samples_and_guided;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 0)
DEF_CONST_INT(NORM_TEX_SLOT, 1)
DEF_CONST_INT(VARIANCE_TEX_SLOT, 2)
DEF_CONST_INT(RAY_COUNTER_SLOT, 3)
DEF_CONST_INT(RAY_LIST_SLOT, 4)
DEF_CONST_INT(TILE_LIST_SLOT, 5)

DEF_CONST_INT(REFL_IMG_SLOT, 6)

INTERFACE_END

#endif // SSR_CLASSIFY_TILES_INTERFACE_GLSL