#ifndef SSR_REPROJECT_INTERFACE_H
#define SSR_REPROJECT_INTERFACE_H

#include "_interface_common.h"

INTERFACE_START(SSRReproject)

struct Params {
    UVEC2_TYPE img_size;
    VEC2_TYPE thresholds;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(DEPTH_TEX_SLOT, 4)
DEF_CONST_INT(NORM_TEX_SLOT, 5)
DEF_CONST_INT(DEPTH_HIST_TEX_SLOT, 6)
DEF_CONST_INT(NORM_HIST_TEX_SLOT, 7)
DEF_CONST_INT(REFL_TEX_SLOT, 8)
DEF_CONST_INT(RAYLEN_TEX_SLOT, 9)
DEF_CONST_INT(REFL_HIST_TEX_SLOT, 10)
DEF_CONST_INT(VELOCITY_TEX_SLOT, 11)
DEF_CONST_INT(VARIANCE_HIST_TEX_SLOT, 12)
DEF_CONST_INT(SAMPLE_COUNT_HIST_TEX_SLOT, 13)
DEF_CONST_INT(TILE_LIST_BUF_SLOT, 14)

DEF_CONST_INT(OUT_REPROJECTED_IMG_SLOT, 0)
DEF_CONST_INT(OUT_AVG_REFL_IMG_SLOT, 1)
DEF_CONST_INT(OUT_VERIANCE_IMG_SLOT, 2)
DEF_CONST_INT(OUT_SAMPLE_COUNT_IMG_SLOT, 3)

INTERFACE_END

#endif // SSR_REPROJECT_INTERFACE_H