#ifndef SSR_BLUR_INTERFACE_GLSL
#define SSR_BLUR_INTERFACE_GLSL

#include "_interface_common.glsl"

INTERFACE_START(SSRBlur)

struct Params {
    UVEC2_TYPE img_size;
    VEC2_TYPE thresholds;
};

DEF_CONST_INT(LOCAL_GROUP_SIZE_X, 8)
DEF_CONST_INT(LOCAL_GROUP_SIZE_Y, 8)

DEF_CONST_INT(ROUGH_TEX_SLOT, 0)
DEF_CONST_INT(REFL_TEX_SLOT, 1)
DEF_CONST_INT(TILE_METADATA_MASK_SLOT, 2)
DEF_CONST_INT(OUT_DENOISED_IMG_SLOT, 3)

INTERFACE_END

#endif // SSR_BLUR_INTERFACE_GLSL