X(Nearest,   VK_FILTER_NEAREST,  VK_SAMPLER_MIPMAP_MODE_NEAREST, GL_NEAREST,                 GL_NEAREST)
X(Bilinear,  VK_FILTER_LINEAR,   VK_SAMPLER_MIPMAP_MODE_NEAREST, GL_LINEAR_MIPMAP_NEAREST,   GL_LINEAR)
X(Trilinear, VK_FILTER_LINEAR,   VK_SAMPLER_MIPMAP_MODE_LINEAR,  GL_LINEAR_MIPMAP_LINEAR,    GL_LINEAR)