X(Repeat,		VK_SAMPLER_ADDRESS_MODE_REPEAT,				GL_REPEAT)
X(ClampToEdge,	VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,		GL_CLAMP_TO_EDGE)
X(ClampToBorder, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,	GL_CLAMP_TO_BORDER)