DECORATE(Repeat,		VK_SAMPLER_ADDRESS_MODE_REPEAT,				GL_REPEAT)
DECORATE(ClampToEdge,	VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_EDGE,		GL_CLAMP_TO_EDGE)
DECORATE(ClampToBorder, VK_SAMPLER_ADDRESS_MODE_CLAMP_TO_BORDER,	GL_CLAMP_TO_BORDER)