#include "test_common.h"

#include <chrono>
#include <future>
#include <istream>

#include "test_scene.h"

void test_shading(Sys::ThreadPool &threads, const bool full) {
    { // complex materials
        run_image_test(threads, "visibility_flags", 25.40, Full);
        run_image_test(threads, "visibility_flags", 25.30, Full_Ultra);
        run_image_test(threads, "two_sided_mat", 39.83, NoShadow);
        run_image_test(threads, "two_sided_mat", 30.05, NoGI);
        run_image_test(threads, "two_sided_mat", 29.60, NoDiffGI);
        run_image_test(threads, "two_sided_mat", 28.05, MedDiffGI);
        run_image_test(threads, "two_sided_mat", 27.30, Full);
        run_image_test(threads, "complex_mat0", 38.55, NoShadow);
        run_image_test(threads, "complex_mat0", 35.35, NoGI);
        run_image_test(threads, "complex_mat0", 29.35, NoDiffGI);
        run_image_test(threads, "complex_mat0", 27.20, MedDiffGI);
        run_image_test(threads, "complex_mat0", 26.05, Full);
        run_image_test(threads, "complex_mat0", 26.30, Full_Ultra);
        run_image_test(threads, "complex_mat1", 35.84, NoShadow);
        run_image_test(threads, "complex_mat1", 34.85, NoGI);
        run_image_test(threads, "complex_mat1", 31.10, NoDiffGI);
        run_image_test(threads, "complex_mat1", 29.74, MedDiffGI);
        run_image_test(threads, "complex_mat1", 28.65, Full);
        run_image_test(threads, "complex_mat1", 29.10, Full_Ultra);
        run_image_test(threads, "complex_mat2", 33.90, NoShadow);
        run_image_test(threads, "complex_mat2", 33.45, NoGI);
        run_image_test(threads, "complex_mat2", 27.25, NoDiffGI);
        run_image_test(threads, "complex_mat2", 25.05, MedDiffGI);
        run_image_test(threads, "complex_mat2", 24.75, Full);
        run_image_test(threads, "complex_mat2", 27.85, Full_Ultra);
        run_image_test(threads, "complex_mat2_spot_light", 34.55, NoShadow);
        run_image_test(threads, "complex_mat2_spot_light", 35.85, NoGI);
        run_image_test(threads, "complex_mat2_spot_light", 30.45, NoDiffGI);
        run_image_test(threads, "complex_mat2_spot_light", 26.70, MedDiffGI);
        run_image_test(threads, "complex_mat2_spot_light", 26.45, Full);
        run_image_test(threads, "complex_mat2_spot_light", 27.80, Full_Ultra);
        run_image_test(threads, "complex_mat2_sun_light", 33.50, NoShadow);
        run_image_test(threads, "complex_mat2_sun_light", 29.15, NoGI);
        run_image_test(threads, "complex_mat2_sun_light", 33.40, NoGI_RTShadow);
        run_image_test(threads, "complex_mat2_sun_light", 21.20, Full);
        run_image_test(threads, "complex_mat2_sun_light", 22.80, Full_Ultra);
        run_image_test(threads, "complex_mat2_moon_light", 22.85, MedDiffGI);
        run_image_test(threads, "complex_mat2_moon_light", 23.05, Full);
        run_image_test(threads, "complex_mat2_moon_light", 23.50, Full_Ultra);
        run_image_test(threads, "complex_mat2_hdri_light", 20.80, MedDiffGI);
        run_image_test(threads, "complex_mat2_hdri_light", 22.60, Full);
        run_image_test(threads, "complex_mat2_hdri_light", 23.95, Full_Ultra);
        run_image_test(threads, "complex_mat2_portal_hdri", 27.25, NoGI);
        run_image_test(threads, "complex_mat2_portal_hdri", 24.40, NoDiffGI);
        run_image_test(threads, "complex_mat2_portal_hdri", 24.50, MedDiffGI);
        run_image_test(threads, "complex_mat2_portal_hdri", 23.90, Full);
        run_image_test(threads, "complex_mat2_portal_hdri", 24.90, Full_Ultra);
        run_image_test(threads, "complex_mat2_portal_sky", 23.55, MedDiffGI);
        run_image_test(threads, "complex_mat2_portal_sky", 24.55, Full);
        run_image_test(threads, "complex_mat2_portal_sky", 25.75, Full_Ultra);
        run_image_test(threads, "complex_mat2_mesh_lights", 20.45, MedDiffGI);
        run_image_test(threads, "complex_mat2_mesh_lights", 20.70, Full);
        run_image_test(threads, "complex_mat2_mesh_lights", 21.55, Full_Ultra);
        run_image_test(threads, "complex_mat3", 24.25, NoShadow);
        run_image_test(threads, "complex_mat3", 21.10, NoGI);
        run_image_test(threads, "complex_mat3", 22.95, NoDiffGI);
        run_image_test(threads, "complex_mat3", 22.55, MedDiffGI);
        run_image_test(threads, "complex_mat3", 22.70, Full);
        run_image_test(threads, "complex_mat3", 23.15, Full_Ultra);
        run_image_test(threads, "complex_mat3_sun_light", 22.40, NoShadow);
        run_image_test(threads, "complex_mat3_sun_light", 17.25, NoGI);
        run_image_test(threads, "complex_mat3_sun_light", 22.70, NoGI_RTShadow);
        run_image_test(threads, "complex_mat3_sun_light", 18.95, Full);
        run_image_test(threads, "complex_mat3_sun_light", 23.80, Full_Ultra);
        run_image_test(threads, "complex_mat3_mesh_lights", 16.90, MedDiffGI);
        run_image_test(threads, "complex_mat3_mesh_lights", 20.45, Full);
        run_image_test(threads, "complex_mat3_mesh_lights", 20.50, Full_Ultra);
        run_image_test(threads, "complex_mat4", 20.25, Full);
        run_image_test(threads, "complex_mat4", 20.25, Full_Ultra);
        run_image_test(threads, "complex_mat4_sun_light", 20.10, Full);
        run_image_test(threads, "complex_mat4_sun_light", 19.90, Full_Ultra);
        run_image_test(threads, "emit_mat0", 24.95, Full);
        run_image_test(threads, "emit_mat0", 25.85, Full_Ultra);
        run_image_test(threads, "emit_mat1", 23.30, Full);
        run_image_test(threads, "emit_mat1", 23.85, Full_Ultra);
    }

    if (!full) {
        return;
    }

    puts(" ---------------");
    /*if (g_tests_success)*/ { // diffuse material
        run_image_test(threads, "diff_mat0", 47.05, NoShadow);
        run_image_test(threads, "diff_mat0", 36.35, NoGI);
        run_image_test(threads, "diff_mat0", 31.50, MedDiffGI);
        run_image_test(threads, "diff_mat0", 28.50, Full);
        run_image_test(threads, "diff_mat1", 46.55, NoShadow);
        run_image_test(threads, "diff_mat1", 35.70, NoGI);
        run_image_test(threads, "diff_mat1", 29.65, MedDiffGI);
        run_image_test(threads, "diff_mat1", 26.65, Full);
        run_image_test(threads, "diff_mat2", 45.30, NoShadow);
        run_image_test(threads, "diff_mat2", 36.00, NoGI);
        run_image_test(threads, "diff_mat2", 31.30, MedDiffGI);
        run_image_test(threads, "diff_mat2", 28.30, Full);
        run_image_test(threads, "diff_mat3", 46.45, NoShadow);
        run_image_test(threads, "diff_mat3", 36.60, NoGI);
        run_image_test(threads, "diff_mat3", 26.25, MedDiffGI);
        run_image_test(threads, "diff_mat3", 22.90, Full);
        run_image_test(threads, "diff_mat4", 47.20, NoShadow);
        run_image_test(threads, "diff_mat4", 35.90, NoGI);
        run_image_test(threads, "diff_mat4", 25.40, MedDiffGI);
        run_image_test(threads, "diff_mat4", 21.25, Full);
        run_image_test(threads, "diff_mat5", 44.60, NoShadow);
        run_image_test(threads, "diff_mat5", 36.35, NoGI);
        run_image_test(threads, "diff_mat5", 26.25, MedDiffGI);
        run_image_test(threads, "diff_mat5", 22.75, Full);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // sheen material
        run_image_test(threads, "sheen_mat0", 46.55, NoShadow);
        run_image_test(threads, "sheen_mat0", 36.95, NoGI);
        run_image_test(threads, "sheen_mat0", 30.35, MedDiffGI);
        run_image_test(threads, "sheen_mat0", 28.85, Full);
        run_image_test(threads, "sheen_mat1", 43.85, NoShadow);
        run_image_test(threads, "sheen_mat1", 36.55, NoGI);
        run_image_test(threads, "sheen_mat1", 27.35, MedDiffGI);
        run_image_test(threads, "sheen_mat1", 26.60, Full);
        run_image_test(threads, "sheen_mat2", 45.30, NoShadow);
        run_image_test(threads, "sheen_mat2", 36.55, NoGI);
        run_image_test(threads, "sheen_mat2", 29.55, MedDiffGI);
        run_image_test(threads, "sheen_mat2", 27.65, Full);
        run_image_test(threads, "sheen_mat3", 43.90, NoShadow);
        run_image_test(threads, "sheen_mat3", 35.95, NoGI);
        run_image_test(threads, "sheen_mat3", 28.35, MedDiffGI);
        run_image_test(threads, "sheen_mat3", 26.40, Full);
        run_image_test(threads, "sheen_mat4", 45.20, NoShadow);
        run_image_test(threads, "sheen_mat4", 37.10, NoGI);
        run_image_test(threads, "sheen_mat4", 25.25, MedDiffGI);
        run_image_test(threads, "sheen_mat4", 21.00, Full);
        run_image_test(threads, "sheen_mat5", 42.30, NoShadow);
        run_image_test(threads, "sheen_mat5", 36.05, NoGI);
        run_image_test(threads, "sheen_mat5", 23.35, MedDiffGI);
        run_image_test(threads, "sheen_mat5", 20.15, Full);
        run_image_test(threads, "sheen_mat6", 44.40, NoShadow);
        run_image_test(threads, "sheen_mat6", 36.75, NoGI);
        run_image_test(threads, "sheen_mat6", 25.00, MedDiffGI);
        run_image_test(threads, "sheen_mat6", 19.90, Full);
        run_image_test(threads, "sheen_mat7", 42.70, NoShadow);
        run_image_test(threads, "sheen_mat7", 36.40, NoGI);
        run_image_test(threads, "sheen_mat7", 24.70, MedDiffGI);
        run_image_test(threads, "sheen_mat7", 19.35, Full);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // specular material
        run_image_test(threads, "spec_mat0", 40.10, NoShadow);
        run_image_test(threads, "spec_mat0", 35.90, NoGI);
        run_image_test(threads, "spec_mat0", 27.10, NoDiffGI);
        run_image_test(threads, "spec_mat0", 24.15, MedDiffGI);
        run_image_test(threads, "spec_mat0", 24.00, Full);
        run_image_test(threads, "spec_mat0", 27.50, Full_Ultra);
        run_image_test(threads, "spec_mat1", 19.60, NoShadow);
        run_image_test(threads, "spec_mat1", 19.40, NoGI);
        run_image_test(threads, "spec_mat1", 22.00, NoDiffGI);
        run_image_test(threads, "spec_mat1", 18.15, MedDiffGI);
        run_image_test(threads, "spec_mat1", 18.05, Full);
        run_image_test(threads, "spec_mat1", 18.80, Full_Ultra);
        run_image_test(threads, "spec_mat2", 44.75, NoShadow);
        run_image_test(threads, "spec_mat2", 35.40, NoGI);
        run_image_test(threads, "spec_mat2", 28.85, NoDiffGI);
        run_image_test(threads, "spec_mat2", 26.20, MedDiffGI);
        run_image_test(threads, "spec_mat2", 25.70, Full);
        run_image_test(threads, "spec_mat2", 25.45, Full_Ultra);
        run_image_test(threads, "spec_mat3", 36.40, NoShadow);
        run_image_test(threads, "spec_mat3", 34.25, NoGI);
        run_image_test(threads, "spec_mat3", 29.00, NoDiffGI);
        run_image_test(threads, "spec_mat3", 21.35, MedDiffGI);
        run_image_test(threads, "spec_mat3", 19.40, Full);
        run_image_test(threads, "spec_mat3", 21.95, Full_Ultra);
        run_image_test(threads, "spec_mat4", 21.00, NoShadow);
        run_image_test(threads, "spec_mat4", 21.10, NoGI);
        run_image_test(threads, "spec_mat4", 21.95, NoDiffGI);
        run_image_test(threads, "spec_mat4", 15.10, MedDiffGI);
        run_image_test(threads, "spec_mat4", 14.25, Full);
        run_image_test(threads, "spec_mat4", 14.35, Full_Ultra);
        run_image_test(threads, "spec_mat5", 32.15, NoShadow);
        run_image_test(threads, "spec_mat5", 30.30, NoGI);
        run_image_test(threads, "spec_mat5", 28.45, NoDiffGI);
        run_image_test(threads, "spec_mat5", 19.80, MedDiffGI);
        run_image_test(threads, "spec_mat5", 18.25, Full);
        run_image_test(threads, "spec_mat5", 18.35, Full_Ultra);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // metal material
        run_image_test(threads, "metal_mat0", 32.65, NoShadow);
        run_image_test(threads, "metal_mat0", 31.65, NoGI);
        run_image_test(threads, "metal_mat0", 29.45, NoDiffGI);
        run_image_test(threads, "metal_mat0", 26.50, MedDiffGI);
        run_image_test(threads, "metal_mat0", 26.15, Full);
        run_image_test(threads, "metal_mat0", 28.75, Full_Ultra);
        run_image_test(threads, "metal_mat1", 23.60, NoShadow);
        run_image_test(threads, "metal_mat1", 23.70, NoGI);
        run_image_test(threads, "metal_mat1", 27.05, NoDiffGI);
        run_image_test(threads, "metal_mat1", 24.85, MedDiffGI);
        run_image_test(threads, "metal_mat1", 24.40, Full);
        run_image_test(threads, "metal_mat1", 24.95, Full_Ultra);
        run_image_test(threads, "metal_mat2", 37.00, NoShadow);
        run_image_test(threads, "metal_mat2", 34.40, NoGI);
        run_image_test(threads, "metal_mat2", 33.55, NoDiffGI);
        run_image_test(threads, "metal_mat2", 31.15, MedDiffGI);
        run_image_test(threads, "metal_mat2", 29.55, Full);
        run_image_test(threads, "metal_mat2", 30.15, Full_Ultra);
        run_image_test(threads, "metal_mat3", 38.05, NoShadow);
        run_image_test(threads, "metal_mat3", 35.10, NoGI);
        run_image_test(threads, "metal_mat3", 30.05, NoDiffGI);
        run_image_test(threads, "metal_mat3", 22.85, MedDiffGI);
        run_image_test(threads, "metal_mat3", 20.20, Full);
        run_image_test(threads, "metal_mat3", 21.70, Full_Ultra);
        run_image_test(threads, "metal_mat4", 25.25, NoShadow);
        run_image_test(threads, "metal_mat4", 25.20, NoGI);
        run_image_test(threads, "metal_mat4", 26.45, NoDiffGI);
        run_image_test(threads, "metal_mat4", 19.70, MedDiffGI);
        run_image_test(threads, "metal_mat4", 17.95, Full);
        run_image_test(threads, "metal_mat4", 17.95, Full_Ultra);
        run_image_test(threads, "metal_mat5", 37.30, NoShadow);
        run_image_test(threads, "metal_mat5", 34.45, NoGI);
        run_image_test(threads, "metal_mat5", 32.50, NoDiffGI);
        run_image_test(threads, "metal_mat5", 24.50, MedDiffGI);
        run_image_test(threads, "metal_mat5", 20.75, Full);
        run_image_test(threads, "metal_mat5", 20.95, Full_Ultra);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // plastic material
        run_image_test(threads, "plastic_mat0", 43.60, NoShadow);
        run_image_test(threads, "plastic_mat0", 36.00, NoGI);
        run_image_test(threads, "plastic_mat0", 32.95, NoDiffGI);
        run_image_test(threads, "plastic_mat0", 28.80, MedDiffGI);
        run_image_test(threads, "plastic_mat0", 27.00, Full);
        run_image_test(threads, "plastic_mat0", 28.20, Full_Ultra);
        run_image_test(threads, "plastic_mat1", 36.20, NoShadow);
        run_image_test(threads, "plastic_mat1", 33.75, NoGI);
        run_image_test(threads, "plastic_mat1", 28.00, NoDiffGI);
        run_image_test(threads, "plastic_mat1", 24.30, MedDiffGI);
        run_image_test(threads, "plastic_mat1", 23.35, Full);
        run_image_test(threads, "plastic_mat1", 23.65, Full_Ultra);
        run_image_test(threads, "plastic_mat2", 41.75, NoShadow);
        run_image_test(threads, "plastic_mat2", 34.90, NoGI);
        run_image_test(threads, "plastic_mat2", 33.40, NoDiffGI);
        run_image_test(threads, "plastic_mat2", 29.25, MedDiffGI);
        run_image_test(threads, "plastic_mat2", 26.55, Full);
        run_image_test(threads, "plastic_mat2", 27.80, Full_Ultra);
        run_image_test(threads, "plastic_mat3", 38.45, NoShadow);
        run_image_test(threads, "plastic_mat3", 34.35, NoGI);
        run_image_test(threads, "plastic_mat3", 31.45, NoDiffGI);
        run_image_test(threads, "plastic_mat3", 24.60, MedDiffGI);
        run_image_test(threads, "plastic_mat3", 21.45, Full);
        run_image_test(threads, "plastic_mat3", 22.70, Full_Ultra);
        run_image_test(threads, "plastic_mat4", 35.75, NoShadow);
        run_image_test(threads, "plastic_mat4", 33.35, NoGI);
        run_image_test(threads, "plastic_mat4", 28.30, NoDiffGI);
        run_image_test(threads, "plastic_mat4", 21.90, MedDiffGI);
        run_image_test(threads, "plastic_mat4", 19.85, Full);
        run_image_test(threads, "plastic_mat4", 20.40, Full_Ultra);
        run_image_test(threads, "plastic_mat5", 42.30, NoShadow);
        run_image_test(threads, "plastic_mat5", 35.25, NoGI);
        run_image_test(threads, "plastic_mat5", 30.40, NoDiffGI);
        run_image_test(threads, "plastic_mat5", 25.40, MedDiffGI);
        run_image_test(threads, "plastic_mat5", 21.10, Full);
        run_image_test(threads, "plastic_mat5", 22.45, Full_Ultra);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // tint material
        run_image_test(threads, "tint_mat0", 43.20, NoShadow);
        run_image_test(threads, "tint_mat0", 35.95, NoGI);
        run_image_test(threads, "tint_mat0", 34.40, NoDiffGI);
        run_image_test(threads, "tint_mat0", 28.10, MedDiffGI);
        run_image_test(threads, "tint_mat0", 26.25, Full);
        run_image_test(threads, "tint_mat1", 32.50, NoShadow);
        run_image_test(threads, "tint_mat1", 31.40, NoGI);
        run_image_test(threads, "tint_mat1", 26.40, NoDiffGI);
        run_image_test(threads, "tint_mat1", 22.75, MedDiffGI);
        run_image_test(threads, "tint_mat1", 21.75, Full);
        run_image_test(threads, "tint_mat2", 40.45, NoShadow);
        run_image_test(threads, "tint_mat2", 34.35, NoGI);
        run_image_test(threads, "tint_mat2", 33.40, NoDiffGI);
        run_image_test(threads, "tint_mat2", 28.95, MedDiffGI);
        run_image_test(threads, "tint_mat2", 26.55, Full);
        run_image_test(threads, "tint_mat3", 43.80, NoShadow);
        run_image_test(threads, "tint_mat3", 36.25, NoGI);
        run_image_test(threads, "tint_mat3", 33.75, NoDiffGI);
        run_image_test(threads, "tint_mat3", 24.90, MedDiffGI);
        run_image_test(threads, "tint_mat3", 19.40, Full);
        run_image_test(threads, "tint_mat4", 30.95, NoShadow);
        run_image_test(threads, "tint_mat4", 30.40, NoGI);
        run_image_test(threads, "tint_mat4", 25.60, NoDiffGI);
        run_image_test(threads, "tint_mat4", 21.45, MedDiffGI);
        run_image_test(threads, "tint_mat4", 17.05, Full);
        run_image_test(threads, "tint_mat5", 41.60, NoShadow);
        run_image_test(threads, "tint_mat5", 34.90, NoGI);
        run_image_test(threads, "tint_mat5", 31.20, NoDiffGI);
        run_image_test(threads, "tint_mat5", 23.80, MedDiffGI);
        run_image_test(threads, "tint_mat5", 17.65, Full);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // clearcoat material
        run_image_test(threads, "coat_mat0", 41.05, NoShadow);
        run_image_test(threads, "coat_mat0", 36.05, NoGI);
        run_image_test(threads, "coat_mat1", 32.05, NoShadow);
        run_image_test(threads, "coat_mat1", 31.25, NoGI);
        run_image_test(threads, "coat_mat2", 28.90, NoShadow);
        run_image_test(threads, "coat_mat2", 28.50, NoGI);
        run_image_test(threads, "coat_mat3", 38.75, NoShadow);
        run_image_test(threads, "coat_mat3", 35.10, NoGI);
        run_image_test(threads, "coat_mat4", 30.85, NoShadow);
        run_image_test(threads, "coat_mat4", 30.55, NoGI);
        run_image_test(threads, "coat_mat5", 28.00, NoShadow);
        run_image_test(threads, "coat_mat5", 27.80, NoGI);
    }
    puts(" ---------------");
    /*if (g_tests_success)*/ { // alpha material
        run_image_test(threads, "alpha_mat0", 37.15, NoShadow);
        run_image_test(threads, "alpha_mat0", 29.75, NoGI);
        run_image_test(threads, "alpha_mat0", 25.55, NoDiffGI);
        run_image_test(threads, "alpha_mat0", 24.75, MedDiffGI);
        run_image_test(threads, "alpha_mat0", 24.80, Full);
        run_image_test(threads, "alpha_mat0", 24.00, Full_Ultra);
        run_image_test(threads, "alpha_mat1", 38.40, NoShadow);
        run_image_test(threads, "alpha_mat1", 30.95, NoGI);
        run_image_test(threads, "alpha_mat1", 28.00, NoDiffGI);
        run_image_test(threads, "alpha_mat1", 26.95, MedDiffGI);
        run_image_test(threads, "alpha_mat1", 27.00, Full);
        run_image_test(threads, "alpha_mat1", 26.45, Full_Ultra);
        run_image_test(threads, "alpha_mat2", 41.30, NoShadow);
        run_image_test(threads, "alpha_mat2", 35.25, NoGI);
        run_image_test(threads, "alpha_mat2", 33.70, NoDiffGI);
        run_image_test(threads, "alpha_mat2", 32.00, MedDiffGI);
        run_image_test(threads, "alpha_mat2", 30.95, Full);
        run_image_test(threads, "alpha_mat2", 31.30, Full_Ultra);
        run_image_test(threads, "alpha_mat3", 46.85, NoShadow);
        run_image_test(threads, "alpha_mat3", 37.60, NoGI);
        run_image_test(threads, "alpha_mat3", 37.60, NoDiffGI);
        run_image_test(threads, "alpha_mat3", 32.25, MedDiffGI);
        run_image_test(threads, "alpha_mat3", 29.00, Full);
        run_image_test(threads, "alpha_mat3", 30.10, Full_Ultra);
    }
}
