name: 'Test Img'
inputs:
  bin-name:
    required: true
  bin-dir:
    required: true
  out-dir:
    required: true
  test-args:
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.bin-dir }}
        path: ${{ inputs.bin-dir }}/
    - run: |
        chmod +x ./${{ inputs.bin-dir }}/${{ inputs.bin-name }}
        REPO_NAME=$(echo "${GITHUB_REPOSITORY}" | cut -d'/' -f2)
        WORK_DIR=`pwd`
        cd ../../builds/$REPO_NAME/assets/shaders
        ln -s ../../src/Eng/renderer/shaders internal
        cd ../textures
        ln -s ../../src/Eng/textures internal
        cd ../../
        cp $WORK_DIR/${{ inputs.bin-dir }}/* ./
        mkdir $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} --prepare_assets pc --norun
        ### Bistro night (dynamic)
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_night_dyn/ -w 1920 -h 1080 --sun_dir 0 1 0 --exposure 3.25 --preset high --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 21.20 21.10 21.05 21.00 20.95 20.95 20.90 20.95 20.95 20.95 21.10 21.25 21.40 21.60 21.70 21.85 21.85 21.75 21.15 20.50 20.00 19.60 20.00 19.70 19.75 19.05 21.00 19.10 17.05 17.00 18.00 18.95 19.40
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_night_dyn/ -w 1920 -h 1080 --sun_dir 0 1 0 --exposure 3.25 --preset ultra --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 21.20 21.10 21.05 21.00 20.95 20.95 20.90 20.95 20.95 20.95 21.10 21.25 21.40 21.60 21.70 21.85 21.85 21.75 21.15 20.50 20.00 19.60 20.05 19.75 19.75 19.05 21.00 19.10 17.05 17.00 18.00 18.95 19.40
        ### Bistro (dynamic)
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_dyn/ -w 1920 -h 1080 --exposure -11 --preset medium --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 20.85 20.70 20.50 20.45 20.45 20.30 20.20 20.30 20.35 20.25 20.35 20.45 20.65 20.80 20.90 21.05 21.15 20.95 20.50 19.75 17.20 17.70 17.95 17.65 18.95 15.90 11.15 9.45 10.65 14.25 16.65 18.60 18.90
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_dyn/ -w 1920 -h 1080 --exposure -11 --preset high --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 21.55 21.35 21.15 21.10 21.00 20.85 20.75 20.80 20.85 20.65 20.80 20.95 21.05 21.15 21.30 21.45 21.60 21.60 21.10 20.10 17.10 17.65 18.05 17.80 19.00 19.25 16.50 14.60 15.70 16.65 18.60 19.80 20.40
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_dyn/ -w 1920 -h 1080 --exposure -11 --preset ultra --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 24.25 23.80 23.45 23.20 23.00 22.80 22.60 22.60 22.55 22.30 22.50 22.60 22.75 22.80 22.85 23.05 23.20 23.10 22.15 20.65 17.35 18.05 18.50 18.30 19.40 19.25 16.35 14.45 15.60 16.70 18.75 20.05 20.80
        ### Coffee maker (dynamic)
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_dyn/ -w 800 -h 1000 --preset medium --no-postprocess --cam_path 0 --psnr 27.80 27.80 27.60 27.20 26.85 26.30 25.95 25.45 25.00 24.30 23.65 23.35 23.65 24.00 23.65 23.35 23.00 23.65 23.75 24.35 24.80 25.40 25.55 25.60 25.65 26.25 26.70 27.20 27.70 28.00 28.30 28.60 28.65
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_dyn/ -w 800 -h 1000 --preset high --no-postprocess --cam_path 0 --psnr 27.75 27.75 27.55 27.15 26.80 26.30 26.05 25.60 25.10 24.40 23.70 23.45 23.75 24.20 23.85 23.60 23.25 23.95 23.95 24.60 25.05 25.60 25.70 25.70 25.75 26.35 26.80 27.35 27.85 28.20 28.45 28.75 28.80
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_dyn/ -w 800 -h 1000 --preset ultra --no-postprocess --cam_path 0 --psnr 27.65 27.65 27.40 27.00 26.65 26.15 25.95 25.50 25.00 24.30 23.60 23.40 23.80 24.20 23.85 23.60 23.20 23.90 23.90 24.55 24.95 25.50 25.60 25.60 25.65 26.25 26.70 27.20 27.70 28.00 28.30 28.60 28.65
        ### Staircase (dynamic)
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_dyn/ -w 720 -h 900 --preset medium --no-postprocess --cam_path 0 --psnr 26.05 25.85 24.90 24.40 24.25 23.90 24.20 24.80 25.30 25.80 23.45 22.10 23.60 23.30 24.15 24.90 24.50 23.90 23.35 23.05 23.05 22.70 22.25 22.40 22.10 21.25 23.00 22.80 23.40 24.55 24.75 24.50 24.90
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_dyn/ -w 720 -h 900 --preset high --no-postprocess --cam_path 0 --psnr 26.85 26.60 25.55 25.05 24.85 24.30 24.45 25.10 25.65 26.25 23.95 22.20 24.25 23.50 24.55 25.45 25.10 25.15 24.50 24.20 24.05 23.25 22.40 22.30 22.25 21.40 23.00 23.20 24.00 25.00 25.25 25.00 25.45
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_dyn/ -w 720 -h 900 --preset ultra --no-postprocess --cam_path 0 --psnr 26.75 26.50 25.50 25.00 24.85 24.25 24.50 25.10 25.60 26.25 23.90 22.05 24.15 23.75 24.85 25.95 25.55 25.60 24.90 24.40 24.15 23.25 22.40 22.30 22.25 21.40 22.95 23.15 24.00 25.05 25.25 25.05 25.55
        ### Sponza (dynamic)
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_dyn/ -w 1920 -h 1080 --exposure -8 --preset medium --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 22.20 21.85 20.65 18.65 20.10 19.20 17.75 18.10 16.30 17.10 16.85 17.85 17.85 17.70 18.20 18.80 18.75 18.20 16.80 15.35 15.15 15.65 16.10 16.35 16.50 16.95 17.55 17.70 18.05 18.75 19.40 19.85 20.10
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_dyn/ -w 1920 -h 1080 --exposure -8 --preset high --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 19.95 19.60 18.85 18.60 18.85 18.85 17.60 17.85 16.30 16.95 16.85 18.10 18.55 18.25 18.95 19.75 19.80 19.55 18.30 17.05 16.80 16.80 16.90 16.85 16.75 17.35 17.90 18.20 18.70 19.50 20.15 20.50 21.00
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_dyn/ -w 1920 -h 1080 --exposure -8 --preset ultra --freeze-sky --no-postprocess --no-fog --cam_path 0 --psnr 20.50 20.10 19.30 19.10 19.55 19.65 18.35 18.90 17.30 17.95 17.65 19.05 19.15 18.75 19.40 20.00 20.10 19.80 18.50 17.25 17.05 17.25 17.60 17.85 17.90 18.90 19.40 19.75 20.20 20.50 21.00 21.15 21.70
        ### Bathroom
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bathroom.json -ref references/bathroom_cycles.uncompressed.png -w 678 -h 900 --preset medium --psnr 17.15 --no-postprocess
        mv bathroom.png bathroom_medium.png
        cp bathroom_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bathroom.json -ref references/bathroom_cycles.uncompressed.png -w 678 -h 900 --preset high --psnr 17.50 --no-postprocess
        mv bathroom.png bathroom_high.png
        cp bathroom_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bathroom.json -ref references/bathroom_cycles.uncompressed.png -w 678 -h 900 --preset ultra --psnr 18.90 --no-postprocess
        mv bathroom.png bathroom_ultra.png
        cp bathroom_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bathroom.json -ref references/bathroom_cycles.uncompressed.png -w 678 -h 900 --pt --psnr 26.90 --no-postprocess
        mv bathroom.png bathroom_pt.png
        cp bathroom_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ### Transparent Machines
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/transparent_machines.json -ref references/transparent_machines_cycles.uncompressed.png -w 1000 -h 1000 --preset high --psnr 20.05 --no-postprocess
        mv transparent_machines.png transparent_machines_high.png
        cp transparent_machines_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/transparent_machines.json -ref references/transparent_machines_cycles.uncompressed.png -w 1000 -h 1000 --preset ultra --psnr 18.30 --no-postprocess
        mv transparent_machines.png transparent_machines_ultra.png
        cp transparent_machines_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ## ai043_01
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_01.json -ref references/ai043_01_cycles.uncompressed.png -w 1400 -h 955 --preset medium --psnr 23.30 --no-postprocess
        mv ai043_01.png ai043_01_medium.png
        cp ai043_01_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_01.json -ref references/ai043_01_cycles.uncompressed.png -w 1400 -h 955 --preset high --psnr 22.05 --no-postprocess
        mv ai043_01.png ai043_01_high.png
        cp ai043_01_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_01.json -ref references/ai043_01_cycles.uncompressed.png -w 1400 -h 955 --preset ultra --psnr 23.00 --no-postprocess
        mv ai043_01.png ai043_01_ultra.png
        cp ai043_01_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ### Bistro night
        #./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_night_cycles.uncompressed.png -w 1920 -h 1080 --sun_dir 0 1 0 --exposure 3.25 --preset medium --psnr 21.30 --freeze-sky --no-postprocess --tex-budget 1024
        #mv bistro.png bistro_night_medium.png
        #cp bistro_night_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_night_cycles.uncompressed.png -w 1920 -h 1080 --sun_dir 0 1 0 --exposure 3.25 --preset high --psnr 23.00 --freeze-sky --no-postprocess --tex-budget 1024
        mv bistro.png bistro_night_high.png
        cp bistro_night_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_night_cycles.uncompressed.png -w 1920 -h 1080 --sun_dir 0 1 0 --exposure 3.25 --preset ultra --psnr 23.00 --freeze-sky --no-postprocess --tex-budget 1024
        mv bistro.png bistro_night_ultra.png
        cp bistro_night_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_night_cycles2.uncompressed.png -w 960 -h 540 --sun_dir 0 1 0 --exposure 3.25 --pt --psnr 26.35 --freeze-sky --no-postprocess
        mv bistro.png bistro_night_pt.png
        cp bistro_night_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ### Coffee maker
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_cycles.uncompressed.png -w 800 -h 1000 --preset medium --psnr 24.70 --no-postprocess
        mv coffee_maker.png coffee_maker_medium.png
        cp coffee_maker_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_cycles.uncompressed.png -w 800 -h 1000 --preset high --psnr 26.05 --no-postprocess
        mv coffee_maker.png coffee_maker_high.png
        cp coffee_maker_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/coffee_maker.json -ref references/coffee_maker_cycles.uncompressed.png -w 800 -h 1000 --preset ultra --psnr 26.20 --no-postprocess
        mv coffee_maker.png coffee_maker_ultra.png
        cp coffee_maker_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ### Staircase
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset medium --psnr 29.40 --no-postprocess
        mv staircase.png staircase_medium.png
        cp staircase_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset high --psnr 29.05 --no-postprocess
        mv staircase.png staircase_high.png
        cp staircase_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset ultra --psnr 29.80 --no-postprocess
        mv staircase.png staircase_ultra.png
        cp staircase_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --pt --psnr 35.60 --no-postprocess
        mv staircase.png staircase_pt.png
        cp staircase_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ### Staircase (mesh lights)
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase2.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset medium --psnr 23.25 --no-postprocess
        mv staircase2.png staircase2_medium.png
        cp staircase2_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase2.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset high --psnr 24.30 --no-postprocess
        mv staircase2.png staircase2_high.png
        cp staircase2_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase2.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --preset ultra --psnr 25.15 --no-postprocess
        mv staircase2.png staircase2_ultra.png
        cp staircase2_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/staircase2.json -ref references/staircase_cycles.uncompressed.png -w 720 -h 900 --pt --psnr 35.90 --no-postprocess
        mv staircase2.png staircase2_pt.png
        cp staircase2_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ### Bistro
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset medium --psnr 22.80 --freeze-sky --no-postprocess
        mv bistro.png bistro_medium.png
        cp bistro_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset high --psnr 23.45 --freeze-sky --no-postprocess
        mv bistro.png bistro_high.png
        cp bistro_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles.uncompressed.png -w 1920 -h 1080 --exposure -11 --preset ultra --psnr 27.10 --freeze-sky --no-postprocess
        mv bistro.png bistro_ultra.png
        cp bistro_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/bistro.json -ref references/bistro_cycles2.uncompressed.png -w 960 -h 540 --exposure -11 --pt --psnr 28.20 --freeze-sky --no-postprocess
        mv bistro.png bistro_pt.png
        cp bistro_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ### Sponza
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset medium --psnr 23.15 --freeze-sky --no-postprocess
        mv sponza.png sponza_medium.png
        cp sponza_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset high --psnr 22.85 --freeze-sky --no-postprocess
        mv sponza.png sponza_high.png
        cp sponza_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles.uncompressed.png -w 1920 -h 1080 --exposure -8 --preset ultra --psnr 24.00 --freeze-sky --no-postprocess
        mv sponza.png sponza_ultra.png
        cp sponza_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/sponza.json -ref references/sponza_cycles2.uncompressed.png -w 960 -h 540 --exposure -8 --pt --psnr 28.10 --freeze-sky --no-postprocess
        mv sponza.png sponza_pt.png
        cp sponza_pt.png $WORK_DIR/${{ inputs.out-dir }}
        ### ai043_06
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 935 --preset medium --psnr 22.85 --no-postprocess
        mv ai043_06.png ai043_06_medium.png
        cp ai043_06_medium.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 935 --preset high --psnr 24.70 --no-postprocess
        mv ai043_06.png ai043_06_high.png
        cp ai043_06_high.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 935 --preset ultra --psnr 26.15 --no-postprocess
        mv ai043_06.png ai043_06_ultra.png
        cp ai043_06_ultra.png $WORK_DIR/${{ inputs.out-dir }}
        ./${{ inputs.bin-name }} ${{ inputs.test-args }} -s scenes/ai043_06.json -ref references/ai043_06_cycles.uncompressed.png -w 1400 -h 935 --pt --psnr 32.65 --no-postprocess
        mv ai043_06.png ai043_06_pt.png
        cp ai043_06_pt.png $WORK_DIR/${{ inputs.out-dir }}
      shell: bash
