
#ifdef _MSC_VER
#pragma warning(disable : 4996)
#endif

#include "Renderer/PrimDraw.cpp"
#include "Renderer/Renderer.cpp"
#include "Renderer/Renderer_DrawList.cpp"
#include "Renderer/Renderer_Frontend.cpp"
#include "Renderer/Renderer_Gen.cpp"
#include "Renderer/Renderer_GIDiffuse.cpp"
#include "Renderer/Renderer_GISpecular.cpp"
#include "Renderer/Renderer_Passes.cpp"
#include "Renderer/Renderer_SunShadows.cpp"

#include "Renderer/Graph/GraphBuilder.cpp"
#include "Renderer/Graph/SubPass.cpp"
#include "Renderer/Passes/RpBuildAccStructures.cpp"
#include "Renderer/Passes/RpCombine.cpp"
#include "Renderer/Passes/RpDebugRT.cpp"
#include "Renderer/Passes/RpDepthFill.cpp"
#include "Renderer/Passes/RpDepthHierarchy.cpp"
#include "Renderer/Passes/RpGBufferFill.cpp"
#include "Renderer/Passes/RpGBufferShade.cpp"
#include "Renderer/Passes/RpOpaque.cpp"
#include "Renderer/Passes/RpSSRCompose.cpp"
#include "Renderer/Passes/RpSSRCompose2.cpp"
#include "Renderer/Passes/RpSampleBrightness.cpp"
#include "Renderer/Passes/RpReadBrightness.cpp"
#include "Renderer/Passes/RpRTGI.cpp"
#include "Renderer/Passes/RpRTReflections.cpp"
#include "Renderer/Passes/RpRTShadows.cpp"
#include "Renderer/Passes/RpShadowMaps.cpp"
#include "Renderer/Passes/RpSkinning.cpp"
#include "Renderer/Passes/RpSkydome.cpp"
#include "Renderer/Passes/RpTransparent.cpp"
#include "Renderer/Passes/RpUpdateAccBuffers.cpp"
#if defined(USE_GL_RENDER) // temporarily gl-only
#include "Renderer/Passes/RpDOF.cpp"
#include "Renderer/Passes/RpFXAA.cpp"
#include "Renderer/Passes/RpResolve.cpp"
#include "Renderer/Passes/RpDebugEllipsoids.cpp"
#include "Renderer/Passes/RpDebugProbes.cpp"
#include "Renderer/Passes/RpDebugTextures.cpp"
#endif

#if defined(USE_GL_RENDER)
#include "Renderer/FrameBufGL.cpp"
#include "Renderer/PrimDrawGL.cpp"
#include "Renderer/RendererGL.cpp"
#include "Renderer/Passes/RpDebugRT_GL.cpp"
#include "Renderer/Passes/RpDebugTexturesGL.cpp"
#include "Renderer/Passes/RpDepthFillGL.cpp"
#include "Renderer/Passes/RpDepthHierarchyGL.cpp"
#include "Renderer/Passes/RpGBufferFillGL.cpp"
#include "Renderer/Passes/RpOpaqueGL.cpp"
#include "Renderer/Passes/RpRTGI_GL.cpp"
#include "Renderer/Passes/RpRTReflections_GL.cpp"
#include "Renderer/Passes/RpRTShadows_GL.cpp"
#include "Renderer/Passes/RpShadowMapsGL.cpp"
#include "Renderer/Passes/RpSkinningGL.cpp"
#include "Renderer/Passes/RpSkydomeGL.cpp"
#include "Renderer/Passes/RpTransparentGL.cpp"

#include "Renderer/Graph/GraphBuilderGL.cpp"
#elif defined(USE_VK_RENDER)
#include "Renderer/FrameBufVK.cpp"
#include "Renderer/PrimDrawVK.cpp"
#include "Renderer/RendererVK.cpp"
#include "Renderer/Passes/RpBuildAccStructuresVK.cpp"
#include "Renderer/Passes/RpDebugRT_VK.cpp"
#include "Renderer/Passes/RpDepthFillVK.cpp"
#include "Renderer/Passes/RpDepthHierarchyVK.cpp"
#include "Renderer/Passes/RpGBufferFillVK.cpp"
#include "Renderer/Passes/RpOpaqueVK.cpp"
#include "Renderer/Passes/RpRTGI_VK.cpp"
#include "Renderer/Passes/RpRTReflections_VK.cpp"
#include "Renderer/Passes/RpRTShadows_VK.cpp"
#include "Renderer/Passes/RpShadowMapsVK.cpp"
#include "Renderer/Passes/RpSkinningVK.cpp"
#include "Renderer/Passes/RpSkydomeVK.cpp"
#include "Renderer/Passes/RpTransparentVK.cpp"
#include "Renderer/Passes/RpUpdateAccBuffersVK.cpp"

#include "Renderer/Graph/GraphBuilderVK.cpp"

#endif