
#pragma warning(disable : 4996)

#include "astc_averages_and_directions.cpp"
#include "astc_block_sizes2.cpp"
#include "astc_color_quantize.cpp"
#include "astc_color_unquantize.cpp"
#include "astc_compress_symbolic.cpp"
#include "astc_compute_variance.cpp"
#include "astc_decompress_symbolic.cpp"
#include "astc_encoding_choice_error.cpp"
#include "astc_find_best_partitioning.cpp"
#include "astc_ideal_endpoints_and_weights.cpp"
#include "astc_image_load_store.cpp"
#include "astc_integer_sequence.cpp"
#include "astc_kmeans_partitioning.cpp"
#include "astc_ktx_dds.cpp"
#include "astc_partition_tables.cpp"
#include "astc_percentile_tables.cpp"
#include "astc_pick_best_endpoint_format.cpp"
#include "astc_quantization.cpp"
#include "astc_stb_tga.cpp"
#include "astc_symbolic_physical.cpp"
#include "astc_toplevel.cpp"
#include "astc_weight_align.cpp"
#include "astc_weight_quant_xfer_tables.cpp"
//#include "exr_to_htga.cpp"
//#include "imgdiff.cpp"
#include "mathlib.cpp"
#include "softfloat.cpp"
#include "stb_image.c"