name: CI

on:
  push:

jobs:
  build-windows-x86_64-gl-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-gl
          path: windows-x86_64-gl/
  build-windows-x86_64-gl-dbg:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Debug"
          bin-dir: "windows-x86_64-gl"
  build-windows-x86_64-gl-dev:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "RelWithDebInfo"
          bin-dir: "windows-x86_64-gl"
  build-windows-x86_64-gl-asan:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Asan"
          bin-dir: "windows-x86_64-gl-asan"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-gl-asan
          path: windows-x86_64-gl-asan/
  build-windows-x86_64-vk-rel:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "windows-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-vk
          path: windows-x86_64-vk/
  build-windows-x86_64-vk-dbg:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Debug"
          bin-dir: "windows-x86_64-vk"
  build-windows-x86_64-vk-dev:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "RelWithDebInfo"
          bin-dir: "windows-x86_64-vk"
  build-windows-x86_64-vk-asan:
    runs-on: [ windows, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-windows
        with:
          cmake-args: "-A x64 -DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Asan"
          bin-dir: "windows-x86_64-vk-asan"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-x86_64-vk-asan
          path: windows-x86_64-vk-asan/
  build-linux-x86_64-gl-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-gl"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-gl
          path: linux-x86_64-gl/
  build-linux-x86_64-gl-dbg:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "Debug"
          bin-dir: "linux-x86_64-gl"
  build-linux-x86_64-gl-dev:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DREN_BACKEND=GL -DCMAKE_UNITY_BUILD=ON"
          config: "RelWithDebInfo"
          bin-dir: "linux-x86_64-gl"
  build-linux-x86_64-vk-rel:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Release"
          bin-dir: "linux-x86_64-vk"
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: linux-x86_64-vk
          path: linux-x86_64-vk/
  build-linux-x86_64-vk-dbg:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "Debug"
          bin-dir: "linux-x86_64-vk"
  build-linux-x86_64-vk-dev:
    runs-on: [ linux, builder ]
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Compile the code
        uses: ./.github/actions/build-linux
        with:
          cmake-args: "-DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON"
          config: "RelWithDebInfo"
          bin-dir: "linux-x86_64-vk"
  # build-macos-universal-vk-rel:
  #   runs-on: [ macos, builder ]
  #   defaults:
  #     run:
  #       shell: bash
  #   steps:
  #     - name: Checkout Workflows
  #       uses: actions/checkout@v4
  #       with:
  #         sparse-checkout: .github
  #     - name: Re-initialize repository
  #       uses: ./.github/actions/checkout
  #     - name: Compile the code
  #       uses: ./.github/actions/build-macos
  #       with:
  #         cmake-args: '-DREN_BACKEND=VK -DCMAKE_UNITY_BUILD=ON -DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"'
  #         config: "Release"
  #         bin-dir: "macos-universal-vk"
  #     - name: Upload artifacts
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: macos-universal-vk
  #         path: macos-universal-vk/
  test-windows-x86_64-gl:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-gl-asan
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-asan
        with:
          bin-dir: "windows-x86_64-gl-asan"
  test-windows-x86_64-vk:
    runs-on: [ windows, x86_64 ]
    needs:
      - build-windows-x86_64-vk-asan
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test-asan
        with:
          bin-dir: "windows-x86_64-vk-asan"
  test-linux-x86_64-gl:
    runs-on: [ linux, x86_64 ]
    needs:
      - build-linux-x86_64-gl-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-gl"
  test-linux-x86_64-vk:
    runs-on: [ linux, x86_64 ]
    needs:
      - build-linux-x86_64-vk-rel
    steps:
      - name: Checkout Workflows
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github
      - name: Re-initialize repository
        uses: ./.github/actions/checkout
      - name: Run Tests
        uses: ./.github/actions/test
        with:
          bin-dir: "linux-x86_64-vk"
